"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart/cart-provider";
import { formatCurrency } from "@/lib/format";

export function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 199 || subtotal === 0 ? 0 : 19.9;
  const total = subtotal + shipping;

  if (!items.length) return <main className="container-shell flex min-h-[60vh] flex-col items-center justify-center py-16 text-center"><span className="flex h-20 w-20 items-center justify-center rounded-full bg-[#fff0e6] text-[#f26822]"><ShoppingBag size={32} /></span><h1 className="mt-6 text-3xl font-black tracking-[-0.06em]">Seu carrinho está vazio</h1><p className="mt-2 max-w-sm text-sm leading-6 text-[#8a8178]">Encontre produtos de lojas independentes e monte seu pedido em poucos cliques.</p><Link href="/" className="mt-7 rounded-full bg-[#f26822] px-6 py-3 text-sm font-black text-white hover:bg-[#d94f0f]">Começar a comprar</Link></main>;

  return <main className="container-shell py-8 md:py-12"><div className="flex flex-col justify-between gap-2 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f26822]">Sua sacola</p><h1 className="mt-2 text-4xl font-black tracking-[-0.07em]">Carrinho</h1></div><p className="text-sm text-[#8a8178]">{items.length} produto(s) selecionado(s)</p></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="grid gap-3">{items.map((item) => <article key={item.id} className="flex gap-4 rounded-2xl border border-[#eee8df] bg-white p-4"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-[#f7f2ec]"><Image src={item.image} alt={item.name} fill sizes="96px" className="object-cover" /></div><div className="min-w-0 flex-1"><p className="text-xs text-[#8a8178]">{item.storeName}</p><h2 className="mt-1 line-clamp-2 font-black">{item.name}</h2><p className="mt-2 font-black text-[#f26822]">{formatCurrency(item.price)}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center rounded-full border border-[#ded6cd]"><button type="button" aria-label="Diminuir quantidade" onClick={() => updateQuantity(item.id, item.quantity - 1)} className="p-2 text-[#5f5852]"><Minus size={14} /></button><span className="min-w-7 text-center text-xs font-black">{item.quantity}</span><button type="button" aria-label="Aumentar quantidade" onClick={() => updateQuantity(item.id, item.quantity + 1)} className="p-2 text-[#5f5852]"><Plus size={14} /></button></div><button type="button" onClick={() => removeItem(item.id)} className="flex items-center gap-1 text-xs font-bold text-[#8a8178] hover:text-[#d94f0f]"><Trash2 size={14} /> Remover</button></div></div></article>)}</div><aside className="h-fit rounded-3xl bg-[#16120f] p-6 text-white lg:sticky lg:top-28"><h2 className="text-xl font-black">Resumo do pedido</h2><div className="mt-6 grid gap-3 border-b border-white/10 pb-5 text-sm"><div className="flex justify-between text-white/65"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between text-white/65"><span>Frete</span><span className={shipping === 0 ? "text-[#7fe0b1]" : ""}>{shipping === 0 ? "Grátis" : formatCurrency(shipping)}</span></div></div><div className="mt-5 flex justify-between text-lg font-black"><span>Total</span><span>{formatCurrency(total)}</span></div><Link href="/checkout" className="mt-6 flex h-13 items-center justify-center gap-2 rounded-full bg-[#f26822] px-5 py-3.5 text-sm font-black text-white hover:bg-[#ff8142]">Finalizar compra <ArrowRight size={17} /></Link><p className="mt-4 text-center text-xs text-white/45">Pagamento demonstrativo em ambiente de apresentação.</p></aside></div></main>;
}
