import type { CatalogCategory, CatalogProduct, CatalogStore } from "@/types/catalog";

export const demoCategories: CatalogCategory[] = [
  { slug: "moda", name: "Moda", eyebrow: "Estilo para você", icon: "✦", tone: "#f9d7c2" },
  { slug: "eletronicos", name: "Eletrônicos", eyebrow: "Tecnologia útil", icon: "◈", tone: "#d9e7f4" },
  { slug: "casa", name: "Casa", eyebrow: "Seu espaço", icon: "⌂", tone: "#e4e3d4" },
  { slug: "beleza", name: "Beleza", eyebrow: "Cuide de você", icon: "✿", tone: "#f0d9e8" },
  { slug: "calcados", name: "Calçados", eyebrow: "Pise com estilo", icon: "◒", tone: "#e9d9c6" },
  { slug: "acessorios", name: "Acessórios", eyebrow: "Detalhes que contam", icon: "◇", tone: "#d9e7dc" },
  { slug: "infantil", name: "Infantil", eyebrow: "Para os pequenos", icon: "✷", tone: "#f4e2a6" },
  { slug: "ferramentas", name: "Ferramentas", eyebrow: "Faça acontecer", icon: "✚", tone: "#d9d9d9" },
  { slug: "rifas", name: "Rifas", eyebrow: "Concorra e acompanhe", icon: "◎", tone: "#f8d7a8" },
];

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=84`;

export const demoProducts: CatalogProduct[] = [
  {
    id: "p-001",
    slug: "moletom-comfy-areia",
    name: "Moletom Comfy Areia",
    category: "Moda",
    storeName: "Casa Norte",
    storeSlug: "casa-norte",
    price: 119.9,
    oldPrice: 159.9,
    installment: "6x de R$ 19,98",
    rating: 4.9,
    reviews: 128,
    sold: "+500 vendidos",
    image: image("photo-1551488831-00ddcb6c6bd3"),
    badge: "Oferta do dia",
    pix: "R$ 113,90 no PIX",
  },
  {
    id: "p-002",
    slug: "fone-bluetooth-wave",
    name: "Fone Bluetooth Wave",
    category: "Eletrônicos",
    storeName: "Conecta Tech",
    storeSlug: "conecta-tech",
    price: 89.9,
    oldPrice: 129.9,
    installment: "5x de R$ 17,98",
    rating: 4.8,
    reviews: 342,
    sold: "+1 mil vendidos",
    image: image("photo-1505740420928-5e560c06d30e"),
    badge: "Mais vendido",
    pix: "R$ 85,40 no PIX",
  },
  {
    id: "p-003",
    slug: "luminaria-orbita",
    name: "Luminária Orbita",
    category: "Casa",
    storeName: "Lume & Lar",
    storeSlug: "lume-e-lar",
    price: 74.9,
    oldPrice: 99.9,
    installment: "4x de R$ 18,72",
    rating: 4.7,
    reviews: 86,
    sold: "+200 vendidos",
    image: image("photo-1507473885765-e6ed057f782c"),
    badge: "-25%",
    pix: "R$ 71,15 no PIX",
  },
  {
    id: "p-004",
    slug: "tenis-urban-sand",
    name: "Tênis Urban Sand",
    category: "Calçados",
    storeName: "Passo Livre",
    storeSlug: "passo-livre",
    price: 169.9,
    oldPrice: 219.9,
    installment: "10x de R$ 16,99",
    rating: 4.9,
    reviews: 204,
    sold: "+800 vendidos",
    image: image("photo-1542291026-7eec264c27ff"),
    badge: "Escolha ATW",
    pix: "R$ 161,40 no PIX",
  },
  {
    id: "p-005",
    slug: "kit-skincare-diario",
    name: "Kit Skincare Diário",
    category: "Beleza",
    storeName: "Pele Real",
    storeSlug: "pele-real",
    price: 97.9,
    oldPrice: 139.9,
    installment: "5x de R$ 19,58",
    rating: 4.8,
    reviews: 97,
    sold: "+300 vendidos",
    image: image("photo-1556229010-6c3f2c9ca5f8"),
    badge: "Novidade",
    pix: "R$ 93,00 no PIX",
  },
  {
    id: "p-006",
    slug: "garrafa-termica-go",
    name: "Garrafa Térmica Go 750ml",
    category: "Casa",
    storeName: "Viva Leve",
    storeSlug: "viva-leve",
    price: 64.9,
    oldPrice: 79.9,
    installment: "3x de R$ 21,63",
    rating: 4.9,
    reviews: 178,
    sold: "+600 vendidos",
    image: image("photo-1602143407151-7111542de6e8"),
    badge: "Frete grátis",
    pix: "R$ 61,65 no PIX",
  },
  {
    id: "p-007",
    slug: "bolsa-mini-caramelo",
    name: "Bolsa Mini Caramelo",
    category: "Acessórios",
    storeName: "Ateliê 27",
    storeSlug: "atelie-27",
    price: 129.9,
    installment: "6x de R$ 21,65",
    rating: 4.8,
    reviews: 61,
    sold: "+100 vendidos",
    image: image("photo-1584917865442-de89df76afd3"),
    badge: "Artesanal",
    pix: "R$ 123,40 no PIX",
  },
  {
    id: "p-008",
    slug: "smartwatch-pulse-fit",
    name: "Smartwatch Pulse Fit",
    category: "Eletrônicos",
    storeName: "Conecta Tech",
    storeSlug: "conecta-tech",
    price: 149.9,
    oldPrice: 199.9,
    installment: "10x de R$ 14,99",
    rating: 4.6,
    reviews: 115,
    sold: "+400 vendidos",
    image: image("photo-1523275335684-37898b6baf30"),
    badge: "Últimas unidades",
    pix: "R$ 142,40 no PIX",
  },
];

export const demoStores: CatalogStore[] = [
  { slug: "casa-norte", name: "Casa Norte", tagline: "Básicos que acompanham você", city: "São Paulo, SP", rating: 4.9, products: 86, initials: "CN", tone: "#1f2522" },
  { slug: "conecta-tech", name: "Conecta Tech", tagline: "Tecnologia sem complicação", city: "Campinas, SP", rating: 4.8, products: 142, initials: "CT", tone: "#f26822" },
  { slug: "atelie-27", name: "Ateliê 27", tagline: "Feito com tempo e intenção", city: "Curitiba, PR", rating: 5, products: 34, initials: "27", tone: "#7f6758" },
  { slug: "lume-e-lar", name: "Lume & Lar", tagline: "Pequenos detalhes, grandes ambientes", city: "Belo Horizonte, MG", rating: 4.9, products: 57, initials: "LL", tone: "#d28f56" },
];
